title: Fuse Guild

description: A dedicated guild on Project 1999, focused on creating a welcoming and supportive environment for all players.
theme: jekyll-theme-chirpy

# Minima theme settings
minima:
  skin: dark
  date_format: "%b %-d, %Y"

# Navigation
navigation_pages:
  - index.md
  - how-to-join.md
  - constitution.md
  - raid-expectations.md
  - dkp-rules.md


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archive settings
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-category
    tag: archive-tag
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'



