title: Fuse - Project 1999 Guild
description: A dedicated guild on Project 1999, focused on creating a welcoming and supportive environment for all players.
theme: minima

# Minima theme settings
minima:
  skin: classic
  date_format: "%b %-d, %Y"
  navigation_pages:
    - index.md
    - finances.md
    - constitution.md
    - raid-expectations.md
    - dkp-rules.md

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag



